server:
  port: 80
  servlet:
    context-path: "/"

spring:
  thymeleaf:
    mode: HTML
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:33306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: cn.sinap.zengblog.domain

logging:
  level:
    root: info
    cn.sinap.zengblog: debug
  file:
    name: log/blog.log

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

comment.avatar: /images/avatar.png






